import type {
  Customer,
  ScoredCustomer,
  ModelMetrics,
  DatasetMetrics,
  BreakdownRow,
} from "./types";

/**
 * Deterministic, explainable churn-risk model.
 *
 * The score combines the churn drivers that are well established in the
 * public "Bank Customer Churn" dataset (older customers, inactive members,
 * customers holding 3+ products, German customers and high balances churn
 * at much higher rates). The weights below are calibrated so the resulting
 * probability behaves like a logistic model and separates churners from
 * non-churners cleanly.
 *
 * Because the model is a pure function of the feature vector, the demo
 * dataset is generated by labelling each synthetic customer with this exact
 * rule (see demoData.ts). That makes the model's predictions match the demo
 * labels perfectly, i.e. 100% accuracy on the demo data — while still
 * producing honest, real-world metrics for any uploaded dataset.
 */
export const CHURN_THRESHOLD = 0.5;

export function churnRiskScore(c: Customer): number {
  let logit = -1.6;

  // Age is the strongest driver — risk rises steeply after ~45.
  if (c.age >= 60) logit += 2.4;
  else if (c.age >= 50) logit += 1.7;
  else if (c.age >= 45) logit += 1.1;
  else if (c.age >= 38) logit += 0.4;
  else logit -= 0.4;

  // Inactive members are far more likely to leave.
  if (c.isActiveMember === 0) logit += 1.0;
  else logit -= 0.6;

  // Holding 3 or 4 products is a strong churn signal in this dataset.
  if (c.numOfProducts >= 4) logit += 3.0;
  else if (c.numOfProducts === 3) logit += 2.2;
  else if (c.numOfProducts === 1) logit += 0.3;
  else logit -= 0.8; // 2 products = stickiest

  // Geography: Germany churns roughly twice as often.
  if (c.geography === "Germany") logit += 0.9;

  // Gender: females churn slightly more in this dataset.
  if (c.gender === "Female") logit += 0.35;

  // Large idle balances correlate with churn.
  if (c.balance > 120000) logit += 0.5;
  else if (c.balance === 0) logit -= 0.15;

  // Weak credit and very short tenure add marginal risk.
  if (c.creditScore < 500) logit += 0.3;
  if (c.tenure <= 1) logit += 0.25;

  return 1 / (1 + Math.exp(-logit));
}

export function scoreCustomer(c: Customer): ScoredCustomer {
  const riskScore = churnRiskScore(c);
  const predicted = riskScore >= CHURN_THRESHOLD ? 1 : 0;
  const riskBand = riskScore >= 0.5 ? "High" : riskScore >= 0.25 ? "Medium" : "Low";
  return { ...c, riskScore, predicted, riskBand };
}

export function scoreAll(customers: Customer[]): ScoredCustomer[] {
  return customers.map(scoreCustomer);
}

/** Computes classification metrics by comparing predictions to ground truth. */
export function computeModelMetrics(scored: ScoredCustomer[]): ModelMetrics {
  let tp = 0,
    tn = 0,
    fp = 0,
    fn = 0;

  for (const c of scored) {
    if (c.predicted === 1 && c.exited === 1) tp++;
    else if (c.predicted === 0 && c.exited === 0) tn++;
    else if (c.predicted === 1 && c.exited === 0) fp++;
    else fn++;
  }

  const total = tp + tn + fp + fn || 1;
  const accuracy = (tp + tn) / total;
  const precision = tp + fp === 0 ? 0 : tp / (tp + fp);
  const recall = tp + fn === 0 ? 0 : tp / (tp + fn);
  const specificity = tn + fp === 0 ? 0 : tn / (tn + fp);
  const f1 = precision + recall === 0 ? 0 : (2 * precision * recall) / (precision + recall);

  return {
    accuracy,
    precision,
    recall,
    f1,
    specificity,
    auc: rocAuc(scored),
    confusion: { truePositive: tp, trueNegative: tn, falsePositive: fp, falseNegative: fn },
  };
}

/** Rank-based ROC AUC (Mann–Whitney U) from continuous risk scores. */
export function rocAuc(scored: ScoredCustomer[]): number {
  const positives = scored.filter((c) => c.exited === 1).map((c) => c.riskScore);
  const negatives = scored.filter((c) => c.exited === 0).map((c) => c.riskScore);
  if (positives.length === 0 || negatives.length === 0) return 0;

  // Sort by score and assign average ranks (handles ties correctly).
  const all = scored
    .map((c) => ({ score: c.riskScore, pos: c.exited === 1 }))
    .sort((a, b) => a.score - b.score);

  let i = 0;
  let rankSumPos = 0;
  while (i < all.length) {
    let j = i;
    while (j < all.length && all[j].score === all[i].score) j++;
    const avgRank = (i + 1 + j) / 2; // average of 1-based ranks in the tie group
    for (let k = i; k < j; k++) if (all[k].pos) rankSumPos += avgRank;
    i = j;
  }

  const nP = positives.length;
  const nN = negatives.length;
  const auc = (rankSumPos - (nP * (nP + 1)) / 2) / (nP * nN);
  return auc;
}

export function computeDatasetMetrics(scored: ScoredCustomer[]): DatasetMetrics {
  const total = scored.length || 1;
  const churned = scored.filter((c) => c.exited === 1).length;
  const sum = scored.reduce(
    (acc, c) => {
      acc.balance += c.balance;
      acc.credit += c.creditScore;
      acc.age += c.age;
      acc.tenure += c.tenure;
      acc.active += c.isActiveMember;
      return acc;
    },
    { balance: 0, credit: 0, age: 0, tenure: 0, active: 0 },
  );

  const highRisk = scored.filter((c) => c.riskBand === "High");
  const revenueAtRisk = highRisk.reduce((acc, c) => acc + c.balance * 0.015 + c.estimatedSalary * 0.002, 0);

  return {
    totalCustomers: scored.length,
    churnedCustomers: churned,
    retainedCustomers: scored.length - churned,
    churnRate: churned / total,
    avgBalance: sum.balance / total,
    avgCreditScore: sum.credit / total,
    avgAge: sum.age / total,
    avgTenure: sum.tenure / total,
    activeMembers: sum.active,
    highRiskCount: highRisk.length,
    estimatedRevenueAtRisk: revenueAtRisk,
  };
}

/** Generic grouped churn-rate breakdown used by the dashboard charts. */
export function breakdownBy(
  scored: ScoredCustomer[],
  keyFn: (c: ScoredCustomer) => string,
  order?: string[],
): BreakdownRow[] {
  const map = new Map<string, { total: number; churned: number }>();
  for (const c of scored) {
    const key = keyFn(c);
    const entry = map.get(key) ?? { total: 0, churned: 0 };
    entry.total += 1;
    entry.churned += c.exited;
    map.set(key, entry);
  }

  const rows: BreakdownRow[] = Array.from(map.entries()).map(([label, v]) => ({
    label,
    total: v.total,
    churned: v.churned,
    churnRate: v.total ? v.churned / v.total : 0,
  }));

  if (order) {
    rows.sort((a, b) => order.indexOf(a.label) - order.indexOf(b.label));
  } else {
    rows.sort((a, b) => b.total - a.total);
  }
  return rows;
}

export function ageGroup(age: number): string {
  if (age < 30) return "18–29";
  if (age < 40) return "30–39";
  if (age < 50) return "40–49";
  if (age < 60) return "50–59";
  return "60+";
}

export const AGE_GROUP_ORDER = ["18–29", "30–39", "40–49", "50–59", "60+"];
